//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: .NET 8.0
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Riders.Mirroring.Desktop.Resources;

using System.Globalization;
using System.Reflection;
using System.Resources;

/// <summary>
/// Strongly-typed access to strings bundled in <c>Resources/Strings.resx</c>
/// and its culture-specific variants (e.g. <c>Strings.fr.resx</c>).
/// </summary>
/// <remarks>
/// WPF picks the culture automatically based on <see cref="CultureInfo.CurrentUICulture"/>.
/// To pin a culture in tests, set <see cref="System.Threading.Thread.CurrentUICulture"/>
/// before the resource is first accessed.
/// </remarks>
public static class Strings
{
    private static ResourceManager? _resourceManager;

    /// <summary>The ResourceManager that backs this strongly-typed accessor.</summary>
    public static ResourceManager ResourceManager
    {
        get
        {
            if (_resourceManager is null)
            {
                ResourceManager temp = new ResourceManager(
                    "Riders.Mirroring.Desktop.Resources.Strings",
                    typeof(Strings).Assembly);
                _resourceManager = temp;
            }
            return _resourceManager;
        }
    }

    /// <summary>Look up a localised string by key, falling back to the invariant culture.</summary>
    public static string? Get(string name) => ResourceManager.GetString(name, CultureInfo.CurrentUICulture);

    // --- Application identity ------------------------------------------------------
    public static string AppTitle => Get(nameof(AppTitle)) ?? "Riders Mirroring";

    // --- Sidebar (MainWindow) -------------------------------------------------------
    public static string SidebarDevicesHeader => Get(nameof(SidebarDevicesHeader)) ?? "DEVICES";
    public static string LogStripLiveLogLabel => Get(nameof(LogStripLiveLogLabel)) ?? "LIVE LOG";
    public static string NavSectionLabel => Get(nameof(NavSectionLabel)) ?? "NAVIGATION";

    // --- AirPlay view ---------------------------------------------------------------
    public static string AirPlayTitle => Get(nameof(AirPlayTitle)) ?? "AirPlay Receiver";
    public static string AirPlayDescription => Get(nameof(AirPlayDescription)) ?? string.Empty;
    public static string AirPlayReceiverStatus => Get(nameof(AirPlayReceiverStatus)) ?? "Receiver status";
    public static string AirPlayConnectedDevices => Get(nameof(AirPlayConnectedDevices)) ?? "Connected devices";
    public static string AirPlayStartButton => Get(nameof(AirPlayStartButton)) ?? "Start";
    public static string AirPlayStopButton => Get(nameof(AirPlayStopButton)) ?? "Stop";

    // --- Mirror view ----------------------------------------------------------------
    public static string MirrorEmptyTitle => Get(nameof(MirrorEmptyTitle)) ?? "No device selected";
    public static string MirrorEmptyDescription => Get(nameof(MirrorEmptyDescription)) ?? string.Empty;
    public static string MirrorEmptyTipHeader => Get(nameof(MirrorEmptyTipHeader)) ?? "Tip";
    public static string MirrorEmptyTipBody => Get(nameof(MirrorEmptyTipBody)) ?? string.Empty;
    public static string MirrorSerialLabel => Get(nameof(MirrorSerialLabel)) ?? "Serial number:";
    public static string MirrorStatusLabel => Get(nameof(MirrorStatusLabel)) ?? "Status:";
    public static string MirrorRunningBadge => Get(nameof(MirrorRunningBadge)) ?? "RUNNING";
    public static string MirrorReadyBadge => Get(nameof(MirrorReadyBadge)) ?? "READY";
    public static string MirrorLatencyBadge => Get(nameof(MirrorLatencyBadge)) ?? string.Empty;
    public static string MirrorStartButton => Get(nameof(MirrorStartButton)) ?? "START MIRRORING";
    public static string MirrorStopButton => Get(nameof(MirrorStopButton)) ?? "STOP MIRRORING";
    public static string MirrorWaitingForVideo => Get(nameof(MirrorWaitingForVideo)) ?? "Waiting for video stream…";
    public static string MirrorSectionStreamingOptions => Get(nameof(MirrorSectionStreamingOptions)) ?? "Streaming options";
    public static string MirrorSectionStreamingOptionsHint => Get(nameof(MirrorSectionStreamingOptionsHint)) ?? string.Empty;
    public static string MirrorOptionKeepAwake => Get(nameof(MirrorOptionKeepAwake)) ?? "Keep the phone screen on";
    public static string MirrorOptionTurnScreenOff => Get(nameof(MirrorOptionTurnScreenOff)) ?? "Turn the phone screen off";
    public static string MirrorOptionAlwaysOnTop => Get(nameof(MirrorOptionAlwaysOnTop)) ?? "Always keep window on top";
    public static string MirrorOptionFullscreen => Get(nameof(MirrorOptionFullscreen)) ?? "Start in fullscreen mode";
    public static string MirrorOptionAudio => Get(nameof(MirrorOptionAudio)) ?? "Forward phone audio";
    public static string MirrorOptionShowTouches => Get(nameof(MirrorOptionShowTouches)) ?? "Show on-screen touches";
    public static string MirrorOptionFpsLabel => Get(nameof(MirrorOptionFpsLabel)) ?? "FPS:";
    public static string MirrorOptionBitrateLabel => Get(nameof(MirrorOptionBitrateLabel)) ?? "Bitrate (Mbps):";
    public static string MirrorOptionResolutionLabel => Get(nameof(MirrorOptionResolutionLabel)) ?? "Max resolution (px):";
    public static string MirrorSectionRemote => Get(nameof(MirrorSectionRemote)) ?? "Remote control";
    public static string MirrorSectionRemoteHint => Get(nameof(MirrorSectionRemoteHint)) ?? string.Empty;
    public static string MirrorSessionInfo => Get(nameof(MirrorSessionInfo)) ?? "Session info";

    // --- Wireless Host view ---------------------------------------------------------
    public static string WirelessHostTitle => Get(nameof(WirelessHostTitle)) ?? "Wireless Host";
    public static string WirelessHostDescription => Get(nameof(WirelessHostDescription)) ?? string.Empty;
    public static string WirelessHostWifiNetwork => Get(nameof(WirelessHostWifiNetwork)) ?? "Wi-Fi network";
    public static string WirelessHostWifiNetworkHint => Get(nameof(WirelessHostWifiNetworkHint)) ?? string.Empty;
    public static string WirelessHostSsidLabel => Get(nameof(WirelessHostSsidLabel)) ?? "SSID";
    public static string WirelessHostPasswordLabel => Get(nameof(WirelessHostPasswordLabel)) ?? "Password";
    public static string WirelessHostOpenNetworksWarning => Get(nameof(WirelessHostOpenNetworksWarning)) ?? string.Empty;
    public static string WirelessHostGenerateButton => Get(nameof(WirelessHostGenerateButton)) ?? "Generate QR code";
    public static string WirelessHostStatusLabel => Get(nameof(WirelessHostStatusLabel)) ?? "Status";

    // --- Settings view --------------------------------------------------------------
    public static string SettingsTitle => Get(nameof(SettingsTitle)) ?? "Settings";
    public static string SettingsDescription => Get(nameof(SettingsDescription)) ?? string.Empty;
    public static string SettingsThemeHeader => Get(nameof(SettingsThemeHeader)) ?? "Theme";
    public static string SettingsThemeHint => Get(nameof(SettingsThemeHint)) ?? string.Empty;
    public static string SettingsAccentColour => Get(nameof(SettingsAccentColour)) ?? "Accent colour";

    // --- About view -----------------------------------------------------------------
    public static string AboutThirdPartyComponents => Get(nameof(AboutThirdPartyComponents)) ?? "Third-party components";
    public static string AboutThirdPartyHint => Get(nameof(AboutThirdPartyHint)) ?? string.Empty;
    public static string AboutColumnComponent => Get(nameof(AboutColumnComponent)) ?? "COMPONENT";
    public static string AboutColumnLicence => Get(nameof(AboutColumnLicence)) ?? "LICENCE";
    public static string AboutColumnUsage => Get(nameof(AboutColumnUsage)) ?? "USAGE";
    public static string AboutGplNote => Get(nameof(AboutGplNote)) ?? string.Empty;
    public static string AboutBuildInfo => Get(nameof(AboutBuildInfo)) ?? "Build information";
    public static string AboutOpenRepo => Get(nameof(AboutOpenRepo)) ?? "Open GitHub repository";
    public static string AboutLicencesButton => Get(nameof(AboutLicencesButton)) ?? "Licences";
}